---
title: 码志
timezone: Asia/Shanghai
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  wiki:
    title: Wiki
    output: true
    permalink: "/wiki/:path/"
baseurl: 
url: https://shuangli88.github.io
date_format: ordinal
subtitle: 打码改变人生
description: 马壮的个人博客
keywords: 码志, Zhuang Ma, mzlogin, mazhuang
encoding: utf-8
side_bar_repo_limit: 5
author: Zhuang Ma
organization: zkh360.com
organization_url: http://www.zkh360.com
github_username: mzlogin
location: Wuhan, China
email: chumpma@gmail.com
navs:
- href: "/"
  label: 首页
- href: "/categories/"
  label: 分类
- href: "/wiki/"
  label: 维基
- href: "/links/"
  label: 链接
- href: "/about/"
  label: 关于
subscribe_rss: "/feed.xml"
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: "/:year/:month/:day/:title/"
gems:
- jekyll-github-metadata
- rouge
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jemoji
repository: mzlogin/mzlogin.github.io
comments_provider: gitalk
disqus:
  username: 
gitment:
  owner: mzlogin
  repo: blog-comments
  oauth:
    client_id: d2e1cbbd298958076462
    client_secret: b42a4178e5fd4a7cf63189ef4b1453b05c375709
gitalk:
  owner: mzlogin
  repo: blog-comments
  clientID: d2e1cbbd298958076462
  clientSecret: b42a4178e5fd4a7cf63189ef4b1453b05c375709
lazy_load_disqus: false
simple_jekyll_search:
  fulltext: false
  limit: 10
google:
  analytics_id: UA-80669434-1
